name: ecolabel_ms
description: "EcoLabel-MS - Application mobile d'évaluation écologique des produits alimentaires"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Networking
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  
  # Image & Camera
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  file_picker: ^8.1.4
  mobile_scanner: ^7.1.4
  
  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.4.3
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # UI Enhancements
  shimmer: ^3.0.0
  
  # Charts
  fl_chart: ^0.68.0
  
  # Animations
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  
  # Share
  share_plus: ^7.2.2
  
  # Screenshot
  screenshot: ^2.3.0
  
  # Social Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  msal_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
